using System;
using System.Collections.Generic;

namespace Leeward.Entity
{
    public class Player
    {
        private readonly int _id;
        
        public int Id => _id;

        private readonly string _name;

        public string Name => _name;

        private List<string> _aliases = new List<string>();

        public Player(string name)
        {
            _id = 1; // TODO: Autogenerated
            _name = name;
        }

        public void SetAlias(string alias)
        {
            lock (_aliases)
            {
                if (!_aliases.Contains(alias))
                    this._aliases.Add(alias); // TODO: Check user unique alias globally?
            }
        }

        public bool Is(string alias)
        {
            lock (_aliases)
            {
                return _aliases.Contains(alias);
            }
        }
    }
}